import type { Complexity } from "./prompt";

/**
 * The full launch content plan: exactly 20 distinct concepts per category,
 * 240 total. Order matters — the first 3 entries of each category are the
 * Stage-1 samples, arranged to cover the category's complexity spread.
 *
 * Distribution rules (tested):
 * - default: 6 toddler · 10 kids · 4 detailed
 * - adults:  0 toddler ·  4 kids · 16 detailed
 * - toddlers: 16 toddler · 4 kids · 0 detailed
 *
 * Every subject prompt is an ORIGINAL design brief — broad themes only,
 * no protected names (enforced by the banned-terms scan in tests).
 */
export interface Concept {
  complexity: Complexity;
  title: string;
  /** The subject description appended to the master prompt. */
  subject: string;
}

/** [complexity, title, subject] shorthand keeps 240 entries readable. */
type C = [Complexity, string, string];

const asConcepts = (rows: C[]): Concept[] =>
  rows.map(([complexity, title, subject]) => ({ complexity, title, subject }));

export const CONCEPTS: Record<string, Concept[]> = {
  "video-games": asConcepts([
    ["toddler", "Game Controller Buddy", "A big smiling video game controller character with large round buttons, a happy face and little arms waving hello."],
    ["kids", "Family Game Night", "A family of four on a cozy couch playing a cooperative video game together, holding controllers, with a simple TV showing an original mountain-and-flag game scene."],
    ["detailed", "Fantasy Platform World", "An original side-scrolling platform game world with floating grassy islands, rope bridges, floating coins, a small waterfall and a flag at the end of the path."],
    ["toddler", "Handheld Console", "A chunky handheld game console with a big empty screen, a directional pad and two large buttons, with a small star floating beside it."],
    ["toddler", "Friendly Gaming Robot", "A round friendly robot holding a game controller, with an antenna, big eyes and a happy smile."],
    ["toddler", "Pixel Star Power-Up", "A large five-pointed star built from big chunky square blocks, sparkling, in an original blocky game style."],
    ["toddler", "Racing Kart", "A simple happy go-kart with very big wheels, a round steering wheel and a small flag on the back."],
    ["toddler", "Treasure Chest Bonus", "A big open treasure chest with round coins and one large gem floating above it, sparkling."],
    ["kids", "Arcade Afternoon", "Two children playing a claw machine in a small arcade, with a plush prize inside and a token cup on the floor."],
    ["kids", "Retro Arcade Cabinet", "A child happily playing an original upright arcade machine with a joystick and big buttons, the screen showing a simple original spaceship game."],
    ["kids", "Space Explorer Game", "An original game scene of a child astronaut avatar hopping between small round planets connected by dotted jump arcs, with stars around."],
    ["kids", "Puzzle Block Land", "Two original round characters stacking giant puzzle pieces and blocks into a tower in a rolling-hills game world."],
    ["kids", "Co-op Adventure Team", "Three child adventurer characters with a rolled map, a lantern and a rope, standing at the entrance of a friendly cave in an original game world."],
    ["kids", "Racing Game Finish Line", "Two original cartoon race cars crossing a checkered finish line with a cheering crowd of round characters and a trophy on a podium."],
    ["kids", "Game Designer at Work", "A child at a desk sketching an original game level on paper, with a computer, a plant and pinned drawings of characters they invented."],
    ["kids", "Gaming Bedroom", "A cozy bedroom with a beanbag chair, a small TV with a game paused on a simple original scene, a shelf of plush toys and a controller on the rug."],
    ["kids", "Treasure Hunt Level", "A child explorer character crossing a rope bridge toward a treasure chest on a cliff, with birds and clouds in an original game landscape."],
    ["detailed", "Grand Arcade Room", "A detailed arcade interior with several original game cabinets, a prize counter with plush toys, a token machine and a patterned carpet."],
    ["detailed", "Sky Castle Final Level", "An original game world castle floating in the clouds with turrets, banners, a rainbow bridge and a friendly round dragon guarding a gate."],
    ["detailed", "Underwater Bonus Level", "An original underwater game level with rings to swim through, bubbles, seaweed, a smiling fish companion and a sunken arch doorway."],
  ]),

  "kids-tv": asConcepts([
    ["toddler", "Smiling TV Set", "A big friendly retro television with rounded corners, two antennas, dials and a happy smiling face on the screen."],
    ["kids", "Cooking Show Friends", "A bear and a rabbit hosting a pretend cooking show at a counter, with a big mixing bowl, a whisk and a cake on a stand."],
    ["detailed", "Puppet Theater Show", "A detailed puppet theater stage with drawn-back curtains, two original hand puppets taking a bow and a small audience of children clapping."],
    ["toddler", "Microphone Mouse", "A little mouse singing happily into one big round microphone with music notes floating around."],
    ["toddler", "Camera Cat", "A friendly cat operating a big rounded TV camera on a tripod, with one paw waving."],
    ["toddler", "Weather Duck", "A duck presenter in a little scarf pointing at a simple weather board showing one big sun and one cloud."],
    ["toddler", "Dancing Bear", "A happy round bear in a fun dance pose with big music notes around it."],
    ["toddler", "Clapperboard Puppy", "A puppy holding a big film clapperboard in its mouth, tail wagging, sitting on a director's cushion."],
    ["kids", "Animal Rescue Team", "Three animal friends — a dog, a beaver and an owl — with a ladder and a rope, helping a kitten down from a tree."],
    ["kids", "Backyard Explorers", "Two children with a magnifying glass and a bug jar exploring tall backyard grass, discovering a friendly snail."],
    ["kids", "Space Crew Show", "An original cartoon crew of animal astronauts — a fox captain, a turtle engineer and a bird navigator — on the bridge of their round spaceship."],
    ["kids", "Craft Time", "Children at a big table making paper crafts with scissors, glue, folded paper boats and a finished paper crown."],
    ["kids", "School Day Adventure", "A cheerful group of kids walking to school together with backpacks, one pulling a wagon with a class project volcano."],
    ["kids", "Music and Dance Show", "A kids' band on a TV stage with a drum, a tambourine and a keyboard, with stage lights and a dancing crowd of children."],
    ["kids", "Problem-Solving Pals", "Animal friends working together to fix a treehouse: a raccoon holding nails, a goat on a ladder and a bird delivering a small hammer."],
    ["kids", "Talent Show Night", "A child juggling three balls on a stage with a drawn curtain, a star backdrop and two friends cheering from the side."],
    ["kids", "Nature Reporters", "A fox holding a microphone interviewing a turtle beside a pond, with a bird holding a small camera."],
    ["detailed", "TV Studio Behind the Scenes", "A detailed television studio with two cameras, hanging lights, a set decorated like a garden, a presenter desk and a crew member with headphones."],
    ["detailed", "Grand Season Finale", "A big finale stage with falling confetti, a full cast of original animal characters holding hands and bowing, and balloons at the sides."],
    ["detailed", "Show Poster Wall", "A wall of framed posters for original imaginary animal shows, each frame showing a simple picture — a boat, a mountain, a star — with a bench and a potted plant below."],
  ]),

  girls: asConcepts([
    ["toddler", "Ballet Slippers", "A pair of ballet slippers with long curly ribbons and a small bow, next to one big star."],
    ["kids", "Soccer Star", "A girl in a jersey kicking a soccer ball toward a goal, hair flying, with a simple field and one cloud."],
    ["detailed", "Fairy Garden Tea Party", "A detailed tea party in a fairy garden: a girl with fairy wings pouring tea for a hedgehog and a bird at a toadstool table with tiny cups and flowers."],
    ["toddler", "Friendly Pony", "A smiling pony with a big flowing mane and tail, standing in grass with one flower."],
    ["toddler", "Cupcake Baker", "A happy girl in an apron holding up one giant cupcake with a swirl of frosting and a cherry."],
    ["toddler", "Butterfly Friend", "A girl with pigtails holding out her finger for one big friendly butterfly to land on."],
    ["toddler", "Smiling Mermaid", "A happy mermaid with a big curved tail waving hello, sitting on a smooth round rock."],
    ["toddler", "Balloon Walk", "A girl in a sun dress happily holding one very big round balloon on a string."],
    ["kids", "Horseback Rider", "A girl in a riding helmet trotting on a horse through a meadow with a fence and a barn in the distance."],
    ["kids", "Young Scientist", "A girl in safety goggles doing a fizzy experiment with two beakers and a bubbling flask on a lab table."],
    ["kids", "Vet for a Day", "A girl with a toy stethoscope examining a patient puppy on a table, with a bandaged teddy bear waiting next in line."],
    ["kids", "Artist at the Easel", "A girl painting a big sunflower on an easel canvas, holding a palette, with paint pots on a stool."],
    ["kids", "Ballet Recital", "A ballerina mid-twirl on a stage in a tutu, arms curved gracefully, with a curtain and stars behind her."],
    ["kids", "Astronaut Dreams", "A girl in a space suit holding her helmet under one arm, waving beside a friendly rocket ready for launch."],
    ["kids", "Fashion Designer Studio", "A girl sketching a dress design at a small desk beside a dress form wearing a work-in-progress gown with pins."],
    ["kids", "Garden Helper", "A girl in boots watering a row of happy flowers with a big watering can, a butterfly overhead."],
    ["kids", "Best Friends Sleepover", "Two girls in pajamas during a sleepover, sitting on pillows with a flashlight, a book and a bowl of popcorn."],
    ["detailed", "Reading Nook Afternoon", "A detailed window-seat reading nook with a girl reading, a sleeping cat, patterned cushions, a mug and rain outside the window."],
    ["detailed", "Band Practice", "Three girls practicing in a garage band with a guitar, a keyboard and a small drum kit, with a rug and posters of shapes on the wall."],
    ["detailed", "Fairy Realm Explorer", "A girl with fairy wings exploring a mushroom village with tiny doors and windows, lantern flowers and a winding path."],
  ]),

  summer: asConcepts([
    ["toddler", "Ice Cream Cone", "One giant happy ice cream cone with three round scoops, a cherry on top and a waffle pattern."],
    ["kids", "Sandcastle Day", "Two kids building a big sandcastle with towers and a flag, with a bucket, a shovel and a starfish nearby."],
    ["detailed", "Tropical Lagoon", "A detailed tropical beach with palm trees, a hammock, scattered seashells, gentle waves, a sailboat on the horizon and two seabirds."],
    ["toddler", "Beach Ball", "One very big striped beach ball sitting on the sand with a small crab beside it."],
    ["toddler", "Sun and Waves", "A big smiling sun with wavy rays above three simple rolling ocean waves."],
    ["toddler", "Flamingo Pool Float", "A big smiling flamingo pool float ring drifting on gentle water with a little splash."],
    ["toddler", "Watermelon Slice", "One giant smiling watermelon slice with big seeds and a small bite taken out."],
    ["toddler", "Seashell Treasure", "One big scalloped seashell on the sand with a little pearl inside and two tiny shells beside it."],
    ["kids", "Lemonade Stand", "Kids running a lemonade stand with a pitcher, cups, a hand-drawn sun decoration and a customer dog waiting politely."],
    ["kids", "Sprinkler Fun", "Children in swimsuits jumping through a backyard sprinkler with big water arcs and a happy dog joining in."],
    ["kids", "Camping Trip", "A family campsite with a dome tent, a safe ringed campfire with marshmallow sticks, a lantern and a curious squirrel."],
    ["kids", "Kite Flying Day", "A child running on a hill flying a big diamond kite with bows on its tail, clouds above."],
    ["kids", "Fishing at the Lake", "A child and grandparent fishing off a wooden dock, with a tackle box, a jumping fish and lily pads."],
    ["kids", "Road Trip", "A happy family car with luggage and a surfboard strapped on the roof, driving past a signpost and cactus hills."],
    ["kids", "Surf Lesson", "A kid balancing on a surfboard riding a gentle friendly wave, arms out, with a dolphin peeking nearby."],
    ["kids", "Picnic in the Park", "Friends on a checkered picnic blanket with a basket, sandwiches, a pie and one curious ant walking off with a crumb."],
    ["kids", "Water Balloon Toss", "Two kids mid-toss in a water balloon game, with a bucket of balloons and one balloon bursting into droplets."],
    ["detailed", "Backyard Summer Party", "A detailed backyard party with a long table, paper lanterns strung between trees, a fruit bowl, a grill with vegetables and dancing guests."],
    ["detailed", "Outdoor Movie Night", "A detailed backyard movie night with a sheet screen showing a simple moon scene, blankets, fairy lights, popcorn bowls and families settling in."],
    ["detailed", "Tide Pool Discovery", "A detailed rocky tide pool with a starfish, a small octopus, anemones, snails and a child crouching with a bucket to look closer."],
  ]),

  adults: asConcepts([
    ["kids", "Friendly Sunflowers", "A cheerful bouquet of three big sunflowers in a simple vase with broad petals and large leaves."],
    ["detailed", "Intricate Floral Mandala", "A circular floral mandala radiating from a center rosette through rings of petals, leaves, teardrops and lace-like scallops, with generous enclosed spaces."],
    ["detailed", "Cozy Reading Nook", "A detailed reading corner with a wingback armchair, a knitted blanket, a side table with a steaming mug, stacked books, a floor lamp and a sleeping cat."],
    ["kids", "Cottage Garden Gate", "A wooden garden gate in a low stone wall with an arch of climbing roses and a path beyond."],
    ["kids", "Decorative Butterfly", "One large butterfly with symmetrical patterned wings of swirls, dots and teardrop shapes."],
    ["kids", "Teatime Still Life", "A decorative teapot with two teacups on saucers, a small cake on a stand and a folded napkin with a simple pattern."],
    ["detailed", "Botanical Garden Path", "A winding path through detailed flower beds of tulips, daisies and hollyhocks, under a pergola with hanging wisteria."],
    ["detailed", "Stained Glass Blossoms", "A stained-glass-inspired panel of magnolia branches, with bold leading lines dividing the background into large glass segments."],
    ["detailed", "Coffee Shop Corner", "A detailed café corner with a counter, a menu board of small pictures, pastries in a glass case, hanging plants and a bar stool by the window."],
    ["detailed", "Mountain Cabin Retreat", "A log cabin by a still lake with pine trees, a canoe at the dock, smoke curling from the chimney and mountains behind."],
    ["detailed", "Victorian Greenhouse", "An ornate glass greenhouse full of potted ferns, hanging baskets, a watering can on a bench and a brick path."],
    ["detailed", "Bookshelf of Treasures", "A tall bookshelf with rows of varied book spines, a globe, a ship in a bottle, a plant and a tiny framed landscape."],
    ["detailed", "Songbirds and Blossoms", "Two decorative songbirds on a flowering cherry branch with patterned feathers and falling petals."],
    ["detailed", "Geometric Tile Pattern", "A repeating geometric tile pattern of interlocking stars, hexagons and diamonds with clean enclosed cells."],
    ["detailed", "Rolling Wave Pattern", "A decorative repeating pattern of stylized ocean waves with curling foam spirals and small fish between the swells."],
    ["detailed", "Lighthouse Cove", "A lighthouse on a rocky cove with a winding stair path, beach grass, gulls and a rowboat pulled onto the shingle."],
    ["detailed", "Elegant Archway", "An ornamental stone archway with carved scrollwork, flanked by potted cypress trees and a lantern hanging in the opening."],
    ["detailed", "Kitchen Herb Shelf", "A rustic kitchen shelf of unlabeled jars, bundled herbs hanging to dry, a mortar and pestle and a honey pot."],
    ["detailed", "Peacock in the Garden", "A decorative peacock with an open patterned tail of eye-spot feathers, standing by a birdbath among rose bushes."],
    ["detailed", "Abstract Flow Pattern", "An abstract full-page pattern of flowing ribbons, spirals and leaf shapes weaving together into large closed regions."],
  ]),

  toddlers: asConcepts([
    ["toddler", "Happy Puppy", "One big happy puppy sitting with floppy ears, a wagging tail and a round nose. No background."],
    ["toddler", "Smiling Cat", "One big smiling cat sitting upright with a curled tail and whiskers. No background."],
    ["kids", "Little Fire Truck", "A friendly fire truck with a ladder, big round wheels and a smiling driver dog, with one small hydrant beside it."],
    ["toddler", "Baby Dinosaur", "One chubby smiling baby dinosaur standing beside its cracked eggshell. No background."],
    ["toddler", "Rubber Duck", "One big rubber duck floating on two simple wavy lines of water."],
    ["toddler", "Teddy Bear", "One big soft teddy bear sitting with open arms and a stitched tummy patch. No background."],
    ["toddler", "Big Red Apple", "One giant apple with a stem, one leaf and a small friendly worm peeking out of a hole."],
    ["toddler", "Birthday Cupcake", "One giant cupcake with a swirl of frosting and a single lit candle on top."],
    ["toddler", "Smiling Sun", "One big smiling sun with fat triangle rays and two small clouds."],
    ["toddler", "Little Fish", "One big round fish with large scales and bubbles, over a single wavy water line."],
    ["toddler", "Baby Elephant", "One happy baby elephant with big ears, its trunk raised, holding a flower. No background."],
    ["toddler", "Big Butterfly", "One big butterfly with two large simple shapes in each wing, flying over one flower."],
    ["toddler", "Hot Air Balloon", "One big hot air balloon with wide vertical stripes and a small basket, with one cloud."],
    ["toddler", "Toy Blocks", "Three big stacked toy blocks, each showing one simple shape: a star, a heart and a circle."],
    ["toddler", "Little House", "One simple house with a big door, two windows, a chimney and one round tree beside it."],
    ["toddler", "Big Flower", "One giant flower with six fat petals, a smiling center, a stem and two leaves."],
    ["toddler", "Choo-Choo Train", "A friendly train engine with a big smokestack puffing three round clouds, on a simple track."],
    ["kids", "Airplane in the Clouds", "A smiling airplane with round windows flying between puffy clouds, with a curved trail behind it."],
    ["kids", "Tractor on the Farm", "A happy tractor with giant back wheels driving past a fence, with one hay bale and a sunflower."],
    ["kids", "Sailboat on the Waves", "A small sailboat with a striped sail riding friendly rolling waves, with a sun and one seagull."],
  ]),

  "fairy-tales": asConcepts([
    ["toddler", "Baby Dragon", "One chubby smiling baby dragon with tiny wings, sitting and hugging its tail. No background."],
    ["kids", "Unicorn Meadow", "A unicorn with a flowing mane standing in a flower meadow under a rainbow, with butterflies around its horn."],
    ["detailed", "Enchanted Castle", "A detailed original enchanted castle with round towers, pennant flags, a drawbridge over a moat with lily pads, and swirling clouds behind."],
    ["toddler", "Magic Wand", "One big star-topped magic wand with ribbon streamers and sparkle bursts around it."],
    ["toddler", "Fairy Toadstool House", "One big toadstool mushroom house with a round door, one window and a tiny chimney."],
    ["toddler", "Royal Crown", "One big royal crown with large round jewels and fleur-shaped points, on a tasseled cushion."],
    ["toddler", "Friendly Frog Prince", "A smiling frog wearing a small crown, sitting on a lily pad with one heart above."],
    ["toddler", "The Magic Key", "One big ornate key with a heart-shaped bow and sparkles, floating above an open storybook."],
    ["kids", "Fairy Garden", "Two fairies watering glowing bell-shaped flowers in a garden with a snail path and a tiny lantern hanging from a branch."],
    ["kids", "Wizard's Library", "A young wizard reading at a desk while three books float around on little wings, with shelves and a telescope."],
    ["kids", "Potion Room", "A cheerful potion room with bubbling round-bellied bottles, a cauldron with star-shaped steam and a shelf of swirl-patterned jars."],
    ["kids", "Princess Forest Walk", "An original princess in a simple gown walking a forest path, greeted by a deer and two birds carrying her ribbon."],
    ["kids", "Prince and the Village", "An original prince helping villagers load apples into a cart beside a bakery with a pretzel-shaped sign."],
    ["kids", "Flying Carpet Ride", "Two children riding a tasseled flying carpet over village rooftops at dusk, with a crescent moon and stars."],
    ["kids", "The Giant Beanstalk", "A child climbing a giant curling beanstalk with huge leaves, up toward a castle on a cloud."],
    ["kids", "Mermaid Lagoon", "Two original mermaids playing in a lagoon with a small waterfall, shell rocks and leaping fish."],
    ["kids", "Woodland Storytime", "A cloaked child reading a storybook aloud to gathered woodland animals — a badger, rabbits and an owl — under a big oak."],
    ["detailed", "Treasure Tower", "A detailed tower room piled with treasure chests, crowns, coin stacks, a sleeping dragon curled around a pearl and a round window showing stars."],
    ["detailed", "Moonlit Fantasy Village", "A detailed original fantasy village at night with crooked chimneys, hanging lanterns, a stone bridge and a wishing well under a full moon."],
    ["detailed", "Dragon's Mountain Perch", "A friendly full-grown dragon perched on a mountain ledge among clouds, with patterned scales and a distant castle below."],
  ]),

  kawaii: asConcepts([
    ["toddler", "Happy Cupcake", "One giant smiling cupcake with a tall frosting swirl, a cherry and small hearts floating around."],
    ["kids", "Boba Tea Buddy", "A big smiling boba tea cup with a wide straw, round pearls at the bottom and a little bow on the lid."],
    ["detailed", "Tiny Bakery", "A detailed cute bakery storefront with an awning, a display window of smiling breads and cakes, a hanging pretzel sign and flower boxes."],
    ["toddler", "Smiling Strawberry", "One giant smiling strawberry with big seeds and a leafy cap, with one small heart."],
    ["toddler", "Happy Toast", "One big smiling slice of toast with a pat of butter on top, arms raised in cheer."],
    ["toddler", "Sleepy Cloud", "One big sleeping cloud with closed eyes and rosy cheeks, with three small stars."],
    ["toddler", "Smiling Star", "One big smiling star with rounded points, surrounded by tiny twinkles."],
    ["toddler", "Happy Mushroom", "One big smiling mushroom with large spots on its cap, standing on a small grass tuft."],
    ["kids", "Cozy Kitten", "A round happy kitten wrapped in a blanket like a burrito, with a mug of warm milk beside it."],
    ["kids", "Puppy with a Bow", "A fluffy round puppy with a big bow on its head, sitting in a teacup."],
    ["kids", "Rainbow and Friends", "A smiling rainbow arching between two happy clouds, with a smiling sun peeking from behind."],
    ["kids", "School Supply Pals", "A smiling pencil, eraser, ruler and notebook standing together like friends, with small stars around."],
    ["kids", "Sushi Family", "A plate of smiling sushi rolls and one happy rice ball with a seaweed belt, with chopsticks resting beside."],
    ["kids", "Ice Cream Twins", "Two smiling ice cream cones side by side holding hands, one with a swirl and one with a round scoop and sprinkles."],
    ["kids", "Happy Houseplant", "A smiling potted plant with heart-shaped leaves in a pot with a simple face, on a windowsill with a watering can."],
    ["kids", "Crescent Moon Dreams", "A smiling crescent moon wearing a nightcap, fishing for stars with a little rod from a cloud."],
    ["kids", "Fruit Friends Picnic", "Smiling fruit friends — a peach, a pineapple and a pair of cherries — sitting on a picnic blanket with tiny sandwiches."],
    ["detailed", "Breakfast Plate Party", "A detailed breakfast spread with a smiling pancake stack, a happy egg, toast, a juice glass with a straw and berries, all with cute faces."],
    ["detailed", "Dessert Parade", "A detailed parade of smiling desserts — a cake float, marching macarons, a donut rolling a hoop — with small flags and balloons."],
    ["detailed", "Bento Box Friends", "A detailed open bento box with compartments of smiling rice, broccoli trees, octopus-shaped sausages and a tiny soy bottle with a face."],
  ]),

  "kids-movies": asConcepts([
    ["toddler", "Popcorn Pal", "One giant smiling popcorn bucket with big fluffy popcorn pieces jumping out happily."],
    ["kids", "Movie Night Fort", "Kids inside a blanket fort with fairy lights and pillows watching a small screen showing a simple rocket scene, sharing popcorn."],
    ["detailed", "Grand Movie Theater", "A detailed movie theater interior with tied curtains, rows of seats, a big blank screen with a star border, wall lamps and an usher with a flashlight."],
    ["toddler", "Film Reel", "One big film reel with a wavy strip of film unrolling, showing empty frames and one star."],
    ["toddler", "Little Movie Camera", "One big friendly vintage movie camera on three tripod legs with a round lens and a small crank."],
    ["toddler", "3D Glasses", "One giant pair of 3D glasses with round lenses and sparkle bursts around them."],
    ["toddler", "Ticket Buddy", "One big smiling admission ticket with a scalloped edge, waving its little arms."],
    ["toddler", "Director's Megaphone", "One big megaphone with a star on its side, next to a folding director's chair."],
    ["kids", "Junior Director", "A child director with a beret and megaphone pointing excitedly, beside a camera on a dolly and a clapperboard."],
    ["kids", "Film Crew in Action", "Three kids filming a scene: one on camera, one holding a boom microphone on a pole, one acting as a knight with a cardboard shield."],
    ["kids", "Drive-In Evening", "A drive-in with two round cars parked in front of a big outdoor screen showing a simple moon-and-stars scene, with a snack tray on a window."],
    ["kids", "Red Carpet Pretend Play", "Kids in dress-up clothes walking a rolled-out carpet, one posing while another snaps a picture with a big camera flash of star shapes."],
    ["kids", "Space Adventure Scene", "A film set of an original space adventure: a child in a cardboard rocket, foil stars hanging from strings and a crew member holding a fan for wind."],
    ["kids", "Jungle Adventure Set", "A film set with cardboard jungle trees, a rope vine swing, a plush toy tiger on a stool and a child explorer with a map."],
    ["kids", "Mystery Detective Story", "A kid detective with a magnifying glass following big paw prints across a room toward a cookie jar, notebook in hand."],
    ["kids", "Comedy Stage Night", "A child comedian on a small stage with a microphone stand, a rubber chicken prop and a laughing audience of kids and a dog."],
    ["kids", "Snack Stand", "A cheerful concession counter with a popcorn machine, a stack of cups, candy jars and a smiling server handing over a treat."],
    ["detailed", "Animation Workshop", "A detailed animation workshop with drawing desks, a lightbox, character sketches pinned to a corkboard, pencil cups and a flipbook mid-flip."],
    ["detailed", "Projection Room", "A detailed old projection room with a big reel projector casting a light beam, stacked film canisters, a rewind bench and a small window to the theater."],
    ["detailed", "Award Night Gala", "A detailed award night stage with a big star trophy on a podium, spotlights, a curtain, an orchestra pit and clapping guests at round tables."],
  ]),

  dinosaurs: asConcepts([
    ["toddler", "Happy T-Rex", "One big happy T-Rex with tiny arms and a huge friendly smile, standing beside one round bush."],
    ["kids", "Triceratops Family", "A triceratops parent and baby walking together through ferns, with three-horned frills and a butterfly leading the way."],
    ["detailed", "Fossil Museum Hall", "A detailed museum hall with a mounted dinosaur skeleton on a platform, information stands with simple pictures, hanging banners and visiting children."],
    ["toddler", "Baby Dino Hatchling", "One chubby baby dinosaur hatching from a big cracked egg, with one shell piece on its head."],
    ["toddler", "Little Stegosaurus", "One smiling stegosaurus with big rounded back plates and a spiky tail, next to one fern."],
    ["toddler", "Smiling Brachiosaurus", "One happy long-necked brachiosaurus reaching up to one tall tree with round leaves."],
    ["toddler", "Baby Pteranodon", "One baby pteranodon with wide-open wings gliding between two puffy clouds."],
    ["toddler", "Round Ankylosaurus", "One round smiling ankylosaurus with big armor bumps and a club tail, standing on simple grass."],
    ["kids", "Parasaurolophus Pond", "A parasaurolophus drinking at a pond with cattails, ripples and a dragonfly hovering above the water."],
    ["kids", "Spinosaurus River", "A spinosaurus with a big back sail wading through a river, gently catching a fish, with palm-like trees on the bank."],
    ["kids", "Velociraptor Race", "Two velociraptors racing side by side across open ground with motion lines, a flag marking the finish by a rock."],
    ["kids", "Dinosaur Family Stroll", "A dinosaur family — two adults and two little ones — strolling in a line through a valley with ferns and a distant waterfall."],
    ["kids", "Watering Hole Gathering", "Different friendly dinosaurs sharing a watering hole: a long-neck drinking, an armored one wading and a small one splashing."],
    ["kids", "Junior Paleontologist", "A child paleontologist with a brush and magnifying glass uncovering a big fossil skeleton in a marked dig square."],
    ["kids", "Volcano Valley", "A gentle volcano puffing one smoke cloud over a valley where two dinosaurs watch from a safe hill with ferns."],
    ["kids", "Pteranodon Sky Glide", "A pteranodon gliding through clouds above a winding river, wings wide, with two babies following behind."],
    ["kids", "Dino Dance Party", "Dinosaurs dancing together in a jungle clearing with stomp lines and music notes, one playing a hollow-log drum."],
    ["detailed", "Excavation Site", "A detailed dig site with a roped grid, trowels and brushes, a wheelbarrow, a half-uncovered skeleton and a tent with a findings table."],
    ["detailed", "Prehistoric Jungle Panorama", "A detailed prehistoric jungle with layered ferns, cycads, a stream, three different dinosaurs at different depths and pterosaurs overhead."],
    ["detailed", "Dinosaur Size Parade", "An educational lineup of five dinosaurs walking in order from smallest to largest across the page, each with distinct patterned skin."],
  ]),

  educational: asConcepts([
    ["toddler", "Count to Five Balloons", "Five big balloons in a row, each printed with one large numeral from 1 to 5, held by a smiling child. The numerals must be correct and clearly drawn."],
    ["kids", "Butterfly Life Cycle", "The life cycle of a butterfly in four connected circles: egg on a leaf, caterpillar, chrysalis and butterfly, joined by arrows around a milkweed plant."],
    ["detailed", "Solar System Tour", "The sun and eight planets in orbit arcs across the page, each planet with its own simple surface pattern, with a small rocket touring past. No labels or text."],
    ["toddler", "Big Shapes", "Four very large shapes side by side with happy faces: a circle, a square, a triangle and a star."],
    ["toddler", "A Is for Apple", "One very large capital letter A beside one big apple with a leaf. The letter must be a correct, clearly drawn capital A."],
    ["toddler", "Rainbow Colors", "One big rainbow with five thick bands arching between two happy clouds."],
    ["toddler", "Three Little Ducklings", "A mother duck followed by exactly three ducklings in a row on a simple pond line."],
    ["toddler", "Fruit and Veggie Friends", "One big apple, one banana and one carrot standing in a row with happy faces."],
    ["kids", "Weather Wheel", "A big wheel divided into four sections showing sunshine, rain, snow and wind, with an arrow pointer and a child in matching clothes beside each section."],
    ["kids", "Plant Growth Steps", "Three flower pots in a row showing a seed sprouting, a small sprout with leaves, and a full flower, with a watering can and sun above."],
    ["kids", "Community Helpers", "A firefighter, a doctor and a mail carrier standing together, each holding one tool of their job: a hose nozzle, a stethoscope and a letter."],
    ["kids", "Musical Instruments Band", "A drum, a guitar, a trumpet and a xylophone arranged together with music notes floating above them."],
    ["kids", "Ocean Animal Friends", "An underwater scene with a whale, a sea turtle, an octopus and a seahorse swimming among seaweed and bubbles."],
    ["kids", "Farm Animal Friends", "A cow, a pig, a sheep and a hen together in a fenced farmyard with a barn and one hay bale."],
    ["kids", "Recycling Helpers", "Two children sorting items into three bins marked with a bottle picture, a paper picture and an apple-core picture. Use pictures on the bins, not words."],
    ["kids", "My Five Senses", "Five circles around a smiling child, each showing one sense: an eye, an ear, a nose, a hand touching a feather and a mouth with an apple."],
    ["kids", "Simple Addition Picnic", "A picnic blanket showing two apples plus three apples with a plus sign and an equals sign leading to five apples. The numerals and signs must be correct."],
    ["detailed", "World Map Adventure", "A simplified decorative world map with the continents as bold friendly shapes, sea waves, a compass rose, a sailing ship and animals on their home continents. No labels."],
    ["detailed", "Science Tools Table", "A detailed science table with a microscope, a magnifying glass, a balance scale, test tubes in a rack and a leaf specimen on a dish."],
    ["detailed", "Alphabet Animal Parade", "A detailed parade of five animals each carrying one large letter in order: A, B, C, D and E — an alligator, a bear, a cat, a dog and an elephant. The letters must be correct and clearly drawn."],
  ]),

  superheroes: asConcepts([
    ["toddler", "Little Flying Hero", "One cheerful cartoon hero character in a simple costume with a flowing cape and a big star on the chest, soaring happily between three puffy clouds with arms spread wide."],
    ["kids", "Storm Rescue Hero", "An original young hero holding a big umbrella shield over a basket of kittens during friendly rain, with a rainbow starting behind."],
    ["detailed", "Secret Headquarters", "A detailed original hero headquarters inside a treehouse with a rope elevator, a map table, a gadget wall, a telescope and a sliding pole."],
    ["toddler", "Hero Mask and Cape", "One big hero mask and one flowing cape with a star clasp, displayed side by side with sparkles."],
    ["toddler", "Super Puppy", "One happy puppy wearing a little cape and mask, leaping over one fire hydrant."],
    ["toddler", "Hero Star Emblem", "One big shield-shaped hero emblem with a star in the middle and rays around it."],
    ["toddler", "Speedy Sneakers", "One giant pair of hero sneakers with little wings on the sides and whoosh lines behind them."],
    ["toddler", "Little Strong Hero", "A smiling toddler hero proudly lifting one giant teddy bear overhead."],
    ["kids", "Plant-Power Hero", "An original hero with leaf-patterned gloves growing a friendly vine to catch a falling flowerpot from a windowsill."],
    ["kids", "Water-Power Hero", "An original hero swirling arcs of water from raised hands to make a rainbow fountain that delights children in a park."],
    ["kids", "Tech Hero Workshop", "A young inventor hero in goggles building a helper gadget at a workbench with springs, bolts and a small robot assistant handing over a wrench."],
    ["kids", "Animal Rescue Hero", "An original hero gently catching a falling kitten in a soft net while birds guide the way, outside an apartment window."],
    ["kids", "Space Hero Patrol", "An original hero in a rounded space suit standing on a small moon, waving at Earth, with a flag showing a heart symbol."],
    ["kids", "Runaway Robot Stop", "A friendly hero gently stopping a wobbling runaway robot with one open hand, while its wheel spins and a bolt pops loose."],
    ["kids", "Park Cleanup Hero", "An original hero and two kids collecting litter into a bag in a park, with a squirrel handing over an acorn cap and a sparkling clean fountain."],
    ["kids", "Hero Training Course", "A young hero mid-leap over foam blocks in a training course with tires, a climbing rope and a coach holding a stopwatch shape."],
    ["kids", "Super Speed Hero", "An original hero running with big friendly motion lines and a trailing cape, racing a laughing dog along a park path."],
    ["detailed", "Team of Young Heroes", "A detailed group pose of five original kid heroes, each with a different simple emblem — a leaf, a droplet, a star, a gear and a paw — on a rooftop at sunrise."],
    ["detailed", "Costume Design Lab", "A detailed costume workshop with a drawing board of cape sketches, a mannequin wearing a work-in-progress suit, fabric rolls, scissors and an emblem stencil sheet."],
    ["detailed", "City Skyline Watch", "A detailed friendly city skyline at dusk with an original hero perched on a rooftop ledge, flags on buildings, water towers and birds settling for the night."],
  ]),
};
